version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        TZ: ${TZ}
    volumes:
      - ./docker/nginx/logs:/etc/nginx/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT_PATH}:/var/www/laravel
    ports:
      - ${WEB_PORT}:80
    links:
      - app
    depends_on:
      - app

  app:
    # container_name: app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        TZ: ${TZ}
    volumes:
      - ${PROJECT_PATH}:/var/www/laravel
    links:
      - db_master
    environment:
      - TZ=${TZ}
      - DB_HOST=${DB_HOST}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}

  db_master:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - TZ=${TZ}
    volumes:
      - ./mnt/mysql:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306

  supervisor:
    build:
      context: ./
      dockerfile: ./docker/supervisor/Dockerfile
    environment:
      - TZ=${TZ}
      - DB_HOST=${DB_HOST}
    volumes:
      - ${PROJECT_PATH}:/var/www/laravel
      - ./docker/supervisor:/etc/supervisor
    links:
      - app
      - db_master
    depends_on:
      - app
