version: "3"

services:
  # swagger:
  #   image: swaggerapi/swagger-editor
  #   # restart: always
  #   ports:
  #     - ${SWAGGER_EDITOR_PORT}:8080

  swagger_ui:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./openapi.app.yaml:/usr/share/nginx/html/openapi.app.yaml
      - ./openapi.admin.yaml:/usr/share/nginx/html/openapi.admin.yaml
    environment:
      API_URL: ${SWAGGER_SPECIFICATION_URL:-openapi.app.yaml}
    ports:
      - ${SWAGGER_UI_PORT:-8082}:8080

  swagger-api:
    image: stoplight/prism:3
    restart: always
    command: mock -h 0.0.0.0 /openapi.app.yaml
    volumes:
      - ./openapi.app.yaml:/openapi.app.yaml
    ports:
      - "${PRISM_PORT:-4010}:4010"
