# envs
# - SYSTEM_NAME
# - ENV_NAME
# - AWS_ECS_CLUSTER_NAME
# - AWS_ECS_BACK_SERVICE_NAME
# - AWS_REGION
region: ap-northeast-1
cluster: "{{ must_env `AWS_ECS_CLUSTER_NAME` }}_{{ must_env `ENV_NAME` }}"
service: "{{ must_env `AWS_ECS_BACK_SERVICE_NAME` }}"
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s

plugins:
  - name: tfstate
    config:
      url: s3://{{ must_env `SYSTEM_NAME` }}-tfstate/work-manager/{{ must_env `ENV_NAME` }}/deploy/ecspresso/data.tfstate
